seed: 2024
train: true
test : False 
total_steps: 1
actor_save_path: "./actor_weights-and-plot/final_weights"
critic_save_path: "./critic_weights-and-plot/final_weights"

env_name: 'Swimmer-v5'
gamma: 0.999
ep_max: 1000
ep_len: 1000
a_lr: 0.0001
c_lr: 0.0001
batch: 512
update_steps: 30
kl : 0
n_neuron : 128

method:
  name: 'clip' # or 'kl_pen'
mepsilon: 0.01
kl_target: 0.1
lam : 0.01

max_grad_norm: 0.5
epsilon: 0.1
temperature_max: 5.0
temperature_min: 0.7
decay_rate : 0.995
Interval_Save : 100

hydra:
  run:
    dir: ./outputs/${now:%m-%d-%H-%M}
  output_subdir: tensorboard
  job:
    chdir: true