# ===============================
#  D3QN Simple Config
# ===============================
config_name: "D3QN simple"
seed: 1
comment: "testing learning_rate effect"

# ---- Network ----
hidden_size1: 128
hidden_size2: 64
hidden_size3: 32

# ---- Training ----
max_episodes: 1000
batch_size: 16
learning_rate: 0.001
memory_size: 100000
target_updates: 20
gamma: 0.99
tau: 0.005

decay_rate: 0.01
cos_amp : 0.5
cos_freq : 0.1
cos_phase : 0.1

# ---- Epsilon ----
epsilon: 1.0
max_epsilon: 1.0
min_epsilon: 0.01
decay_rate1: 0.012

# ---- Environment ----
env_name: "LunarLander-v3"
gravity: -9.8
enable_wind: true
wind_power: 10.0
turbulence_power: 1.5
continuous: false
render_mode_train: null
render_mode_test: "human"

# ---- Misc ----
device: cuda
train_start: 1000
train: true
test: false
save_path: "./weights/final_weights"
load_path: "./weights/final_weights"
save_interval: 100
sma_window: 50
myAl: true
done_lag : true
done : true

# ===============================
#  Hydra Output Settings
# ===============================
hydra:
  sweep:
    dir: ./outputs/${now:%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  run:
    dir: ./outputs/${now:%m-%d-%H-%M-%S}/single_run
  job:
    chdir: true
