# ===============================
#  D3QN Simple Config
# ===============================
config_name: "D3QN simple"
seed: 1
comment: ""

# ---- Network ----
hidden_size1: 128
hidden_size2: 64
hidden_size3: 32

# ---- Training ----
max_episodes: 1500
batch_size: 64
learning_rate: 0.001
memory_capacity: 100000   
target_updates: 20
discount_factor : 0.99
tau: 0.005
max_steps: 1000          
update_frequency: 30        
clip_grad_norm: 3
learn_frequency: 8

# ---- Temperature ----
periodic_decay: 0.01
cos_amp : 0.5
cos_freq : 0.1
cos_phase : 0.1
tempertuer_max : 1
min_temperature : 0.01

# ---- Epsilon ----
epsilon_max: 1.0
min_epsilon: 0.01
epsilon_decay: 0.012

# ---- Environment ----
env_name: "LunarLander-v3"
gravity: -9.8
enable_wind: false
wind_power: 10.0
turbulence_power: 1.5
continuous: false
render_mode_train: null
render_mode_test: "human"

# ---- Misc ----
device: cuda
train_start: 1000
train: true
test: false
save_path: "./weights/final_weights"
load_path: "./weights/final_weights"
save_interval: 100
sma_window: 50
myAl: true

epsilon_greedy      : true
render_fps          : 0
render              : render
indricing_Ep_Or_temp: True

# ===============================
#  Hydra Output Settings
# ===============================
hydra:
  sweep:
    dir: ./outputs/${now:%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  run:
    dir: ./outputs/${now:%m-%d-%H-%M-%S}/single_run
  job:
    chdir: true