seed: 1
hidden_size1: 128
hidden_size2: 64
hidden_size3: 32
max_episodes: 600
batch_size: 256
epsilon: 1.0

max_epsilon: 1.0
min_epsilon: 0.01
memory_size: 100000
learning_rate: 0.001
target_updates: 20

device : cuda
gamma: 0.99
train_start: 1000 # improtant for MASP
tau: 1

decay_rate1: 0.015
decay_rate: 0.01
cos_amp : 0.5
cos_freq : 0.2
cos_phase : 0.5

train: true
test : False
myAl : True

# "LunarLander-v2" ,"ALE/Breakout-v5"
env_name: "LunarLander-v3"
obs_type: "grayscale" # Change to "ram" for RAM observations
render_mode_train: null
render_mode_test: "human"
save_path: "./weights/final_weights"
load_path: "./weights/final_weights"
save_interval: 100
sma_window: 50

hydra:
  run:
    dir: ./outputs/${now:%m-%d-%H-%M}
  job:
    chdir: true